### ISSUE TITLE
Could not connect to the server:

### ISSUE THREAD

**Issue by DrFrankxio** [bym-refitted/bymr-desktop-launcher#5]
Could not connect to the server:
This is the proof:
![image](https://github.com/user-attachments/assets/1a6f2417-504c-478b-ae65-c2acde1e0ebd)
And i cant do anything, login, request password, register, etc. Is completely broken.

**Comment by DrFrankxio** [comment]
The connection opened yesterday, but today from 19:30 getting same error:
![image](https://github.com/user-attachments/assets/d4958410-555b-4c9f-bafd-28ae1a24ea33)
![image](https://github.com/user-attachments/assets/b952fe8a-07ec-462d-844e-9e9657d7e958)
![image](https://github.com/user-attachments/assets/f5d9a4e5-9aa7-4149-9e1f-7d6ed2fef921)

**Comment by React1-X** [comment]
@DrFrankxio - I assume you are connected now? I can close this?
